<a href="https://colab.research.google.com/github/Ruthmwaura/Moringa-Week-5-Project/blob/main/week_5_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#importing libraries that will be used 
import pandas as pd
import numpy as np

#loading data to the environment
covid_df=pd.read_csv('/content/owid-covid-data.csv')
covid_df.head()

  iso_code continent  ... excess_mortality excess_mortality_cumulative_per_million
0      AFG      Asia  ...              NaN                                     NaN
1      AFG      Asia  ...              NaN                                     NaN
2      AFG      Asia  ...              NaN                                     NaN
3      AFG      Asia  ...              NaN                                     NaN
4      AFG      Asia  ...              NaN                                     NaN

[5 rows x 67 columns]

In [10]:
#dropping columns
#the columns are  Irrelevant to our analysis
covid_df.drop(['iso_code','new_deaths_smoothed','new_cases_smoothed','new_cases_smoothed_per_million','new_deaths_smoothed_per_million','new_tests_smoothed','new_tests_smoothed_per_thousand','new_vaccinations_smoothed','new_vaccinations_smoothed_per_million','new_people_vaccinated_smoothed','new_people_vaccinated_smoothed_per_hundred','aged_70_older','icu_patients','icu_patients_per_million','hosp_patients','hosp_patients_per_million','weekly_icu_admissions','weekly_icu_admissions_per_million','weekly_hosp_admissions','weekly_hosp_admissions_per_million','new_tests','total_tests','total_tests_per_thousand','new_tests_per_thousand','positive_rate','tests_per_case','tests_units','median_age','extreme_poverty','cardiovasc_death_rate','diabetes_prevalence','female_smokers','male_smokers','handwashing_facilities','hospital_beds_per_thousand','life_expectancy','human_development_index','excess_mortality_cumulative_absolute','excess_mortality_cumulative','excess_mortality','excess_mortality_cumulative_per_million'], axis = 1, inplace = True)
covid_df.head(3)

  continent     location  ... aged_65_older  gdp_per_capita
0      Asia  Afghanistan  ...         2.581        1803.987
1      Asia  Afghanistan  ...         2.581        1803.987
2      Asia  Afghanistan  ...         2.581        1803.987

[3 rows x 26 columns]

In [11]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163318 entries, 0 to 163317
Data columns (total 26 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   continent                            153531 non-null  object
 1   location                             163318 non-null  object
 2   date                                 163318 non-null  object
 3   total_cases                          160326 non-null  float64
 4   new_cases                            160246 non-null  float64
 5   total_deaths                         142603 non-null  float64
 6   new_deaths                           142758 non-null  float64
 7   total_cases_per_million              159581 non-null  float64
 8   new_cases_per_million                159501 non-null  float64
 9   total_deaths_per_million             141871 non-null  float64
 10  new_deaths_per_million               142026 non-null  float64
 11  reproduction_rate                    123563 non-null  float64
 12  total_vaccinations                   43773 non-null   float64
 13  people_vaccinated                    41651 non-null   float64
 14  people_fully_vaccinated              39025 non-null   float64
 15  total_boosters                       16441 non-null   float64
 16  new_vaccinations                     36251 non-null   float64
 17  total_vaccinations_per_hundred       43773 non-null   float64
 18  people_vaccinated_per_hundred        41651 non-null   float64
 19  people_fully_vaccinated_per_hundred  39025 non-null   float64
 20  total_boosters_per_hundred           16441 non-null   float64
 21  stringency_index                     127605 non-null  float64
 22  population                           162256 non-null  float64
 23  population_density                   145259 non-null  float64
 24  aged_65_older                        133890 non-null  float64
 25  gdp_per_capita                       136004 non-null  float64
dtypes: float64(23), object(3)
memory usage: 32.4+ MB